default: &default
  adapter:  mysql2
  encoding: utf8
  pool:     5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host:     <%= ENV['DATABASE_HOSTNAME'] %>
  database: webapp

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  database: webapp_test
