# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4b333c1ad87c741f6a0cd7017fe3c97c4a9de5b5a064eee95e6990aa03b6a5f9e02c4965b80a02fe6242497450a1521ef75b2b866178fc44df801706fcb1254c

test:
  secret_key_base: 048ec3779828085aba768a4bdf93725d61aa963f53c4e4495ae6bc1ce8eb1501827db0ebf5e61a95c1b702faf64408aec3d7afd42894beb5cfc5c51f809807d9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
